testapache2:
  build: .
  ports:
   - "5000:80"
  environment:
    DB_HOST: "dockermysql2"
    DB_USER: "dockertest"
    DB_PASS: "dockertest"
    DB_NAME: "dockertest"

  links:
   - dockermysql2

dockermysql2:
  build: ./db/
  environment:
    MYSQL_DATABASE: "dockertest"
    MYSQL_USER: "dockertest"
    MYSQL_PASSWORD: "dockertest"
    MYSQL_ROOT_PASSWORD: "dockertest"
